#include <linux/module.h>
#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <asm/uaccess.h>
#include <linux/mutex.h>
#include <linux/slab.h>
#include <linux/fs.h>
#include <linux/cdev.h>

#include <rtai.h>
#include <rtai_fifos.h>
#include <rtai_sched.h>

#include <linux/comedilib.h>

#include "moduledef.h"

#ifdef ENABLE_COMPUTATION
#ifndef ENABLE_LOOKUPTABLES
#include <rtai_math.h>
#endif
#endif


MODULE_LICENSE( "GPL" );
MODULE_DESCRIPTION( "Dynamic clamp for RELACS" );
MODULE_AUTHOR( "Jan Benda <jan.benda@uni-tuebingen.de>" );


///////////////////////////////////////////////////////////////////////////////
// *** TYPE DEFINITIONS ***
///////////////////////////////////////////////////////////////////////////////

// subdevice acquisition errors:
#define E_COMEDI    -1
#define E_NODATA    -2
#define E_UNDERRUN  -3
#define E_OVERFLOW  -4


// DAQ-DEVICES:

struct chanT {
  int subdev;
  unsigned int chan;
  int param;
  int modelIndex;
  int statusIndex;
  int isUsed;
  comedi_insn insn;
  lsampl_t lsample;
  struct converterT converter;
  float scale;
  float voltage;
  float prevvoltage;
  int trigger;
  float alevel;
};

struct subdeviceT {
  int subdev;
  enum subdevTypes type;
  unsigned int fifo;
  unsigned int sampleSize;
  unsigned int frequency;
  long delay;
  long duration;           // => relative to index of dynclamp-Task
  int continuous;
  int startsource;
  int used;
  int prepared;
  int running;
  int pending;
  int error;               // E_COMEDI, E_NODATA, ...
  unsigned int chanN;
  struct chanT chanlist[MAXCHANLIST];
};

struct triggerT {
  int enabled;
  int subdev;
  unsigned int chan;
  float alevel;
};


// RTAI TASK:

struct dynClampTaskT {
  RT_TASK rtTask;
  unsigned int periodLengthNs;
  unsigned int reqFreq;
  unsigned int setFreq;
  unsigned long duration;
  int continuous;
  int running;
  unsigned long loopCnt;
  long aoIndex;
};



///////////////////////////////////////////////////////////////////////////////
// *** GLOBAL VARIABLES ***
///////////////////////////////////////////////////////////////////////////////

struct cdev *rtcdev;
struct mutex mutex;

// DAQ-DEVICES:

comedi_t *device;
char devname[DEV_NAME_MAXLEN+1];

int subdevices[MAXSUBDEV];
int subdevN = 0;
struct subdeviceT aisubdev;
struct subdeviceT aosubdev;
int reqCloseSubdev = -1;

struct triggerT trigger;

char statusInputNames[MAXCHANLIST][PARAM_NAME_MAXLEN];
char statusInputUnits[MAXCHANLIST][PARAM_NAME_MAXLEN];
float statusInput[MAXCHANLIST];
int statusInputN = 0;
#ifdef ENABLE_INTERVALS
int intervalstatusinx = 0;
#endif
#ifdef ENABLE_AITIME
int aitimestatusinx = 0;
#endif
#ifdef ENABLE_AIACQUISITIONTIME
int aiacquisitiontimestatusinx = 0;
#endif
#ifdef ENABLE_AICONVERSIONTIME
int aiconversiontimestatusinx = 0;
#endif
#ifdef ENABLE_AOTIME
int aotimestatusinx = 0;
#endif
#ifdef ENABLE_MODELTIME
int modeltimestatusinx = 0;
#endif
#ifdef ENABLE_COMPUTATION
int outputstatusinx = 0;
#endif

#ifdef ENABLE_COMPUTATION
int traceIndex = 0;
int chanIndex = 0;

#ifdef ENABLE_LOOKUPTABLES
int lookupinx = 0;
int lookupn[MAXLOOKUPTABLES];
float* lookupx[MAXLOOKUPTABLES];
float* lookupy[MAXLOOKUPTABLES];
#endif

#endif

// RTAI TASK:

struct dynClampTaskT dynClampTask;

// TTL pulse generation:
#ifdef ENABLE_TTLPULSE
comedi_insn ttlStartWriteInsn[MAXTTLPULSES];
comedi_insn ttlEndWriteInsn[MAXTTLPULSES];
comedi_insn ttlStartReadInsn[MAXTTLPULSES];
comedi_insn ttlEndReadInsn[MAXTTLPULSES];
comedi_insn ttlStartAOInsn[MAXTTLPULSES];
comedi_insn ttlEndAOInsn[MAXTTLPULSES];

comedi_insn *ttlInsns[MAXTTLPULSETYPES];

lsampl_t ttlLow = 0;
lsampl_t ttlHigh = 1;
#endif

#ifdef ENABLE_SYNCSEC
int syncSECPulse = 20000;  /*! Length of the inject pulse generated by the SEC in ns. */
comedi_insn syncSECInsnLow;
comedi_insn syncSECInsnHigh;
lsampl_t syncSECLow = 0;
lsampl_t syncSECHigh = 1;
#endif


// for debug:

char *iocNames[RTMODULE_IOC_MAXNR] = {
  "dummy",
  "IOC_OPEN_SUBDEV", "IOC_CHANLIST", "IOC_SYNC_CMD",
  "IOC_START_SUBDEV", "IOC_CHK_RUNNING", "IOC_REQ_CLOSE", "IOC_STOP_SUBDEV",
  "IOC_DIO_CMD", "IOC_SET_TRIGGER", "IOC_UNSET_TRIGGER", "IOC_GET_TRACE_INFO",
  "IOC_SET_TRACE_CHANNEL", "IOC_GETRATE", "IOC_GETLOOPCNT", "IOC_GETAOINDEX",
  "IOC_SET_LOOKUP_K", "IOC_SET_LOOKUP_N", "IOC_SET_LOOKUP_X", "IOC_SET_LOOKUP_Y"
};


///////////////////////////////////////////////////////////////////////////////
// *** PROTOTYPES ***
///////////////////////////////////////////////////////////////////////////////

int dynclampmodule_open( struct inode *devFile, struct file *fModule );
int dynclampmodule_close( struct inode *devFile, struct file *fModule );
#ifdef HAVE_UNLOCKED_IOCTL
long dynclampmodule_unlocked_ioctl( struct file *fModule, unsigned int cmd,
				    unsigned long arg );
#else
int dynclampmodule_ioctl( struct inode *devFile, struct file *fModule, 
			  unsigned int cmd, unsigned long arg );
#endif
static struct file_operations fops = {                     
  .owner = THIS_MODULE,
#ifdef HAVE_UNLOCKED_IOCTL
  .unlocked_ioctl = dynclampmodule_unlocked_ioctl,
#else
  .ioctl = dynclampmodule_ioctl,
#endif
  .open = dynclampmodule_open, 
  .release = dynclampmodule_close,
};

int openComediDevice( struct deviceIOCT *deviceIOC );
int openComediSubDevice( const char *devicename, int subdev, char *errorstr );
void releaseSubdevice( int subdev );
void releaseAnalogSubdevice( struct subdeviceT *subdev );

int loadChanList( struct chanlistIOCT *chanlistIOC, struct subdeviceT *subdev );
int loadSyncCmd( struct syncCmdIOCT *syncCmdIOC, struct subdeviceT *subdev );
int startSubdevice( struct subdeviceT *subdev );
int stopSubdevice( struct subdeviceT *subdev, int kill );
void dynclamp_loop( long dummy );
int init_dynclamp_loop( void );
void cleanup_dynclamp_loop( void );

int setDigitalIO( struct dioIOCT *dioIOC );

int setAnalogTrigger( struct triggerIOCT *triggerIOC );
int unsetAnalogTrigger( struct triggerIOCT *triggerIOC );


///////////////////////////////////////////////////////////////////////////////
// *** MODEL INCLUDE ***
///////////////////////////////////////////////////////////////////////////////
#ifdef ENABLE_COMPUTATION
#include "model.c"
float origParamOutput[PARAMOUTPUT_N];
#endif

///////////////////////////////////////////////////////////////////////////////
// *** HELPER FUNCTIONS ***
///////////////////////////////////////////////////////////////////////////////

void init_globals( void )
{
  int k;
  char name[PARAM_NAME_MAXLEN];

  device = 0;
  memset( subdevices, 0, sizeof(subdevices) );
  subdevN = 0;
  memset( &aisubdev, 0, sizeof(aisubdev) );
  memset( &aosubdev, 0, sizeof(aosubdev) );
  aisubdev.subdev = -1;
  aosubdev.subdev = -1;
  reqCloseSubdev = -1;
  memset( &dynClampTask, 0, sizeof(struct dynClampTaskT ) );

  statusInputN = 0;
#ifdef ENABLE_INTERVALS
  intervalstatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[intervalstatusinx], "Interval" );
  strcpy( statusInputUnits[intervalstatusinx], "s" );
  statusInput[intervalstatusinx] = 0.0;
#endif
#ifdef ENABLE_AITIME
  aitimestatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[aitimestatusinx], "AI-time" );
  strcpy( statusInputUnits[aitimestatusinx], "s" );
  statusInput[aitimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AIACQUISITIONTIME
  aiacquisitiontimestatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[aiacquisitiontimestatusinx], "AI-acquisition-time" );
  strcpy( statusInputUnits[aiacquisitiontimestatusinx], "s" );
  statusInput[aiacquisitiontimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AICONVERSIONTIME
  aiconversiontimestatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[aiconversiontimestatusinx], "AI-conversion-time" );
  strcpy( statusInputUnits[aiconversiontimestatusinx], "s" );
  statusInput[aiconversiontimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AOTIME
  aotimestatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[aotimestatusinx], "AO-time" );
  strcpy( statusInputUnits[aotimestatusinx], "s" );
  statusInput[aotimestatusinx] = 0.0;
#endif
#ifdef ENABLE_MODELTIME
  modeltimestatusinx = statusInputN;
  statusInputN++;
  strcpy( statusInputNames[modeltimestatusinx], "Model-time" );
  strcpy( statusInputUnits[modeltimestatusinx], "s" );
  statusInput[modeltimestatusinx] = 0.0;
#endif
#ifdef ENABLE_COMPUTATION
  outputstatusinx = statusInputN;
  for ( k=0; k<OUTPUT_N; k++ ) {
    sprintf( name, "Stimulus-%s", outputNames[k] );
    strcpy( statusInputNames[statusInputN], name );
    strcpy( statusInputUnits[statusInputN], outputUnits[k] );
    statusInput[statusInputN] = 0.0;
    statusInputN++;
    sprintf( name, "Model-%s", outputNames[k] );
    strcpy( statusInputNames[statusInputN], name );
    strcpy( statusInputUnits[statusInputN], outputUnits[k] );
    statusInput[statusInputN] = 0.0;
    statusInputN++;
    sprintf( name, "Total-%s", outputNames[k] );
    strcpy( statusInputNames[statusInputN], name );
    strcpy( statusInputUnits[statusInputN], outputUnits[k] );
    statusInput[statusInputN] = 0.0;
    statusInputN++;
#ifdef ENABLE_SYNCSEC
    sprintf( name, "Injected-%s", outputNames[k] );
    strcpy( statusInputNames[statusInputN], name );
    strcpy( statusInputUnits[statusInputN], outputUnits[k] );
    statusInput[statusInputN] = 0.0;
    statusInputN++;
#endif
  }
#endif

#ifdef ENABLE_COMPUTATION
  traceIndex = 0;
  chanIndex = 0;
#ifdef ENABLE_LOOKUPTABLES
  lookupinx = 0;
  for ( k=0; k<MAXLOOKUPTABLES; k++ ) {
    lookupn[k] = 0;
    if ( lookupx[lookupinx] != NULL ) {
      kfree( lookupx[lookupinx] );
      lookupx[lookupinx] = NULL;
    }
    if ( lookupy[lookupinx] != NULL ) {
      kfree( lookupy[lookupinx] );
      lookupy[lookupinx] = NULL;
    }
  }
#endif
#endif

#ifdef ENABLE_TTLPULSE
  ttlInsns[0] = ttlStartWriteInsn;
  ttlInsns[1] = ttlEndWriteInsn;
  ttlInsns[2] = ttlStartReadInsn;
  ttlInsns[3] = ttlEndReadInsn;
  ttlInsns[4] = ttlStartAOInsn;
  ttlInsns[5] = ttlEndAOInsn;
#endif
#ifdef ENABLE_SYNCSEC
  memset( &syncSECInsnLow, 0, sizeof(comedi_insn) );
  syncSECInsnLow.insn = INSN_WRITE;
  syncSECInsnLow.subdev = -1;
  syncSECInsnLow.n = 1;
  syncSECInsnLow.data = &syncSECLow;
  memset( &syncSECInsnHigh, 0, sizeof(comedi_insn) );
  syncSECInsnHigh.insn = INSN_WRITE;
  syncSECInsnHigh.subdev = -1;
  syncSECInsnHigh.n = 1;
  syncSECInsnHigh.data = &syncSECHigh;
#endif
}


///////////////////////////////////////////////////////////////////////////////
// *** DAQ FUNCTIONS ***
///////////////////////////////////////////////////////////////////////////////

int openComediDevice( struct deviceIOCT *deviceIOC )
{
  struct subdeviceT *subdev;
  int retval;

  if ( deviceIOC->subdevType == SUBDEV_IN || deviceIOC->subdevType == SUBDEV_OUT ) {

    if ( deviceIOC->subdevType == SUBDEV_OUT )
      subdev = &aosubdev;
    else
      subdev = &aisubdev;

    // initialize subdevice structure:
    subdev->used = 1;
    subdev->subdev = deviceIOC->subdev;
    subdev->type = deviceIOC->subdevType;
    subdev->fifo = -1; 
    subdev->delay = -1; 
    subdev->duration = -1;
    subdev->startsource = 0;
    subdev->running = 0;
    subdev->chanN = 0;

    retval = openComediSubDevice( deviceIOC->devicename, deviceIOC->subdev, deviceIOC->errorstr );
    if ( retval < 0 )
      return -EFAULT;

    // create FIFO for subdevice:
    subdev->fifo = deviceIOC->subdev;
    retval = rtf_create( subdev->fifo, FIFO_SIZE );
    if ( retval ) {
      sprintf( deviceIOC->errorstr, "failed to create fifo with %d bytes for subdevice %i, device %s.",
	       FIFO_SIZE, deviceIOC->subdev, devname );
      ERROR_MSG( "openComediDevice ERROR: %s\n", deviceIOC->errorstr );
      return -EFAULT;
    }
    else
      DEBUG_MSG( "openComediDevice: Created FIFO with %d bytes buffer size for subdevice %i, device %s\n",
		 FIFO_SIZE, deviceIOC->subdev, devname );

    // pass FIFO properties to user:
    deviceIOC->fifoIndex = subdev->fifo;
    deviceIOC->fifoSize = FIFO_SIZE;
  }
  else {
    deviceIOC->fifoIndex = 0;
    deviceIOC->fifoSize = 0;

    retval = openComediSubDevice( deviceIOC->devicename, deviceIOC->subdev, deviceIOC->errorstr );
    if ( retval < 0 )
      return retval;
  }

  return 0;
}


int openComediSubDevice( const char *devicename, int subdev, char *errorstr )
{
  int iS;

  // add to list (on error releaseSubdevice needs to be able to remove it from list!):
  if ( subdevN == MAXSUBDEV ) {
    sprintf( errorstr, "maximum number %d of supported subdevices exceeded for comedi subdevice %i on device %s.",
	     MAXSUBDEV, subdev, devicename );
    ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
    return -ENOMEM;
  }
  subdevices[subdevN] = subdev;
  subdevN++;

  if ( device ) {
    if ( strcmp( devicename, devname ) == 0 ) {
      DEBUG_MSG( "openComediSubDevice: device %s is opened already\n", 
		 devname );
    }
    else {
      sprintf( errorstr, "a different comedi device, %s, is opened already.", devname );
      ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
      return -EINVAL;
    }
  }

  if ( ! device ) {
    // open comedi device:
    device = comedi_open( devicename );
    if ( ! device ) {
      sprintf( errorstr, "failed to open comedi device %s.", devicename );
      ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
      comedi_perror( "dynclampmodule: comedi_open" );    
      return -EFAULT;
    }
    strncpy( devname, devicename, DEV_NAME_MAXLEN );
    DEBUG_MSG( "openComediSubDevice: opened device %s\n",  devname );
  }

  // check subdev index:
  if ( subdev < 0 || 
       subdev >= comedi_get_n_subdevices( device ) ) {
    sprintf( errorstr, "invalid comedi subdevice %i on device %s requested.",
	     subdev, devicename );
    ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
    return -EINVAL;
  }

  // subdevice already opened?
  for ( iS=0; iS<subdevN-1; iS++ ) {
    if ( subdevices[iS] == subdev ) {
      sprintf( errorstr, "comedi subdevice %i on device %s already in use.",
	       subdev, devicename );
      ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
      return -EBUSY;
    }
  }

  // lock requested subdevice:
  if ( comedi_lock( device, subdev ) != 0 ) {
    sprintf( errorstr, "failed to lock comedi subdevice %i on device %s.",
	     subdev, devicename );
    ERROR_MSG( "openComediSubDevice: %s\n", errorstr );
    return -EFAULT;
  }

  DEBUG_MSG( "openComediSubDevice: locked subdevice %i on device %s\n", 
             subdev, devname );

  return 0;
}


void releaseSubdevice( int subdev )
{
  int iS;
  int subdevinx;
#ifdef ENABLE_TTLPULSE
  int pT;
  int iT;
  int k;
  int retVal;
#endif

  if ( subdevN <= 0 ) {
    ERROR_MSG( "releaseSubdevice ERROR: no subdevices registered!\n" );
    return;
  }

  subdevinx = -1;
  for ( iS = 0; iS < subdevN; iS++ ) {
    if ( subdevices[iS] == subdev ) {
      subdevinx = iS;
      break;
    }
  }
  if ( subdevinx < 0 ) {
    ERROR_MSG( "releaseSubdevice ERROR: subdevice %d not in use!\n", subdev );
    return;
  }

  DEBUG_MSG( "releaseSubdevice: release subdevice %d on device %s\n", subdev, devname );

  // stop analog subdevices:
  if ( aisubdev.subdev == subdev )
    releaseAnalogSubdevice( &aisubdev );
  else if ( aosubdev.subdev == subdev )
    releaseAnalogSubdevice( &aosubdev );
  
  // unlock subdevice:
  if ( device && comedi_unlock( device, subdev ) < 0 )
    WARN_MSG( "releaseSubdevice WARNING: failed to unlock subdevice %d on device %s!\n",
	      subdev, devname );
  else
    DEBUG_MSG( "releaseSubdevice: successfully unlocked subdevice %d on device %s!\n",
	       subdev, devname );

#ifdef ENABLE_TTLPULSE
  // remove ttl pulses:
  for ( pT = 0; pT < MAXTTLPULSETYPES; pT++ ) {
    for ( iT = 0; iT < MAXTTLPULSES && ttlInsns[pT][iT].n > 0; ) {
      if ( ttlInsns[pT][iT].subdev == subdev ) {
	/* set low: */
	ttlInsns[pT][iT].data = &ttlLow;
	retVal = comedi_do_insn( device, &ttlInsns[pT][iT] );
	if ( retVal < 1 ) {
	  if ( retVal < 0 )
	    comedi_perror( "dynclampmodule: releaseSubdevice() -> clearing ttl pulse: comedi_do_insn" );
	  ERROR_MSG( "releaseSubdevice(): ERROR! failed to set TTL pulse %d low\n", iT );
	}
	/* remove from list: */
	for ( k = iT+1; k < MAXTTLPULSES; k++ )
	  ttlInsns[pT][k-1] = ttlInsns[pT][k];
	ttlInsns[pT][MAXTTLPULSES-1].n = 0;
      }
      else
	iT++;
    }
  }
#endif

  // remove from list:
  for ( iS = subdevinx; iS<subdevN-1; iS++ )
    subdevices[iS] = subdevices[iS+1];
  subdevN--;
  DEBUG_MSG( "releaseSubdevice: released subdevice %d, new subdevN=%d\n", subdev, subdevN );

  // still some subdevices in use:
  if ( subdevN > 0 )
    return;

  // close comedi device:
  DEBUG_MSG( "releaseSubdevice: release comedi device for last subdev id %d\n", subdev );
  if ( device && comedi_close( device ) < 0 )
    WARN_MSG( "releaseSubdevice WARNING: failed to close comedi device %s!\n", devname );
  else
    DEBUG_MSG( "releaseSubdevice: successfully closed comedi device %s!\n", devname );
  device = 0;
  devname[0] = '\0';
}


void releaseAnalogSubdevice( struct subdeviceT *subdev )
{
  if ( subdev->running ) {
    DEBUG_MSG( "releaseAnalogSubdevice: stop and potentially kill subdevice %d\n", subdev->subdev );
    stopSubdevice( subdev, /*kill=*/1 );
  }
  // delete FIFO:
  rtf_destroy( subdev->fifo );
  // reset subdevice structure:
  memset( subdev, 0, sizeof(struct subdeviceT) );
  subdev->subdev = -1;
}


int loadChanList( struct chanlistIOCT *chanlistIOC, struct subdeviceT *subdev )
{
  int iC, isC;
  int trig = 0;
#ifdef ENABLE_COMPUTATION
  int i;
#endif

  if ( subdev->subdev < 0 || !subdev->used ) {
    ERROR_MSG( "loadChanList ERROR: First open an appropriate device and subdevice. Chanlist not loaded!\n" );
    return -EFAULT;
  }
  if ( subdev->running ) {
    ERROR_MSG( "loadChanList ERROR: subdevice %i on device %s already running.\n",
	       subdev->subdev, devname );
    return -EBUSY;
  }
  if ( chanlistIOC->chanlistN > MAXCHANLIST ) {
    ERROR_MSG( "loadChanList ERROR: Invalid chanlist length for subdevice %i on device %s. Chanlist not loaded!\n",
	       subdev->subdev, devname );
    return -ENOMEM;
  }

  // check for trigger:
  if ( trigger.enabled ) {
    if ( trigger.subdev >= 0 ) {
      if ( subdev->subdev == trigger.subdev )
	trig = 1;
    }
    else {
      if ( subdev->type == SUBDEV_IN )
	trig = 1;
    }
    DEBUG_MSG( "loadChanList: checked for trigger on subdevice %d: %d\n", subdev->subdev, trig );
  }

  if ( subdev->chanN > 0 ) {
    // subdev chanlist already exist
    for ( iC = 0; iC < chanlistIOC->chanlistN; iC++ ) {
      for ( isC = 0; isC < subdev->chanN; isC++ ) {
        if ( CR_CHAN(chanlistIOC->chanlist[iC]) == 
	     subdev->chanlist[isC].chan + PARAM_CHAN_OFFSET*subdev->chanlist[isC].param ) {
	  subdev->chanlist[isC].isUsed = 1;
	  if ( trig && subdev->chanlist[iC].chan == trigger.chan ) {
	    DEBUG_MSG( "loadChanList: set trigger for channel %d id %d on subdevice %d with level %d\n", subdev->chanlist[iC].chan, iC, subdev->subdev, (int)(100.0*trigger.alevel) );
	    subdev->chanlist[iC].trigger = 1;
	    subdev->chanlist[iC].alevel = trigger.alevel;
	  }
	  else {
	    subdev->chanlist[iC].trigger = 0;
	    subdev->chanlist[iC].alevel = 0.0;
	  }
	  subdev->chanlist[isC].scale = chanlistIOC->scalelist[iC];
	  if ( subdev->chanlist[isC].param == 0 ) {
	    subdev->chanlist[isC].insn.chanspec = chanlistIOC->chanlist[iC];
	    memcpy( &subdev->chanlist[iC].converter, &chanlistIOC->conversionlist[iC], sizeof(struct converterT) );
	  }
	  break;
        }
      }
    }
  }
  else {
    
    // create and initialize chanlist for subdevice:
    memset( subdev->chanlist, 0, sizeof(subdev->chanlist) );
    subdev->chanN = chanlistIOC->chanlistN;
    
    for ( iC=0; iC < subdev->chanN; iC++ ) {
      subdev->chanlist[iC].subdev = subdev->subdev;
      subdev->chanlist[iC].chan = CR_CHAN( chanlistIOC->chanlist[iC] );
      subdev->chanlist[iC].lsample = 0;
      memset( &subdev->chanlist[iC].insn, 0, sizeof(comedi_insn) );
      subdev->chanlist[iC].param = subdev->chanlist[iC].chan/PARAM_CHAN_OFFSET;
      subdev->chanlist[iC].modelIndex = -1;
      subdev->chanlist[iC].statusIndex = -1;
      subdev->chanlist[iC].scale = chanlistIOC->scalelist[iC];
      subdev->chanlist[iC].isUsed = 1; 
      subdev->chanlist[iC].voltage = 0.0; 
      subdev->chanlist[iC].prevvoltage = 0.0;
      if ( trig && subdev->chanlist[iC].chan == trigger.chan ) {
	DEBUG_MSG( "loadChanList: added trigger to channel %d id %d on subdevice %d with level %d\n", subdev->chanlist[iC].chan, iC, subdev->subdev, (int)(100.0*trigger.alevel) );
	subdev->chanlist[iC].trigger = 1;
	subdev->chanlist[iC].alevel = trigger.alevel;
      }
      else {
	subdev->chanlist[iC].trigger = 0;
	subdev->chanlist[iC].alevel = 0.0;
      }
      if ( subdev->chanlist[iC].param > 0 ) {
	subdev->chanlist[iC].chan %= PARAM_CHAN_OFFSET;
	memset( &subdev->chanlist[iC].converter, 0, sizeof( struct converterT ) );
      }
      else {
	if ( subdev->type == SUBDEV_IN ) {
	  subdev->chanlist[iC].insn.insn = INSN_READ;
#ifdef ENABLE_COMPUTATION
	  for ( i = 0; i < INPUT_N; i++ ) {
	    if ( inputChannels[i] == subdev->chanlist[iC].chan )
	      subdev->chanlist[iC].modelIndex = i;
	  }
#endif
	}
	else {
	  subdev->chanlist[iC].insn.insn = INSN_WRITE;
#ifdef ENABLE_COMPUTATION
	  for ( i = 0; i < OUTPUT_N; i++ ) {
	    if ( outputChannels[i] == subdev->chanlist[iC].chan ) {
	      subdev->chanlist[iC].modelIndex = i;
#ifdef ENABLE_SYNCSEC
	      subdev->chanlist[iC].statusIndex = outputstatusinx + 4*i;
#else
	      subdev->chanlist[iC].statusIndex = outputstatusinx + 3*i;
#endif
	    }
	  }
#endif
	}
	subdev->chanlist[iC].insn.n = 1;
	subdev->chanlist[iC].insn.data = &subdev->chanlist[iC].lsample;
	subdev->chanlist[iC].insn.subdev = subdev->subdev;
	subdev->chanlist[iC].insn.chanspec = chanlistIOC->chanlist[iC];
	memcpy( &subdev->chanlist[iC].converter, &chanlistIOC->conversionlist[iC], sizeof(struct converterT) );
      }
    }
  }    
  return 0;
}


int loadSyncCmd( struct syncCmdIOCT *syncCmdIOC, struct subdeviceT *subdev )
{
  if ( subdev->subdev < 0 || !subdev->used ) {
    ERROR_MSG( "loadSyncCmd ERROR: first open an appropriate device and subdevice. Sync-command not loaded!\n" );
    return -EFAULT;
  }
  if ( subdev->running ) {
    ERROR_MSG( "startSubdevice ERROR: subdevice %i on device %s already running.\n",
	       subdev->subdev, devname );
    return -EBUSY;
  }
  if ( subdev->chanN <= 0 || !subdev->chanlist ) {
    ERROR_MSG( "loadSyncCmd ERROR: first load Chanlist for subdevice %i on device %s. Sync-command not loaded!\n",
	       subdev->subdev, devname );
    return -EFAULT;
  }
  if ( syncCmdIOC->frequency > MAX_FREQUENCY ) {
    ERROR_MSG( "loadSyncCmd ERROR: requested frequency is above MAX_FREQUENCY (%d Hz). Sync-command not loaded!\n",
	       MAX_FREQUENCY );
    return -EINVAL;
  }

  // initialize sampling parameters for subdevice:
  subdev->frequency = syncCmdIOC->frequency > 0 ? syncCmdIOC->frequency : dynClampTask.setFreq;
  subdev->delay = syncCmdIOC->delay;
  subdev->duration = syncCmdIOC->duration;
  subdev->continuous = syncCmdIOC->continuous;
  subdev->startsource = syncCmdIOC->startsource;
  subdev->pending = 0;

  DEBUG_MSG( "loadSyncCmd: loaded %ld samples with startsource %d for subdevice %d\n",
	     subdev->duration, subdev->startsource, subdev->subdev );

  // test requested sampling-rate and set frequency for dynamic clamp task:
  if ( !dynClampTask.reqFreq ) {
    dynClampTask.reqFreq = subdev->frequency;
  }
  else {
    if ( dynClampTask.setFreq != subdev->frequency ) {
      ERROR_MSG( "loadSyncCmd ERROR: requested frequency %u Hz of subdevice %i on device %s is inconsistent to frequency %u Hz of other subdevice. Sync-command not loaded!\n",
		 subdev->frequency, subdev->subdev, devname, dynClampTask.setFreq );
      return -EINVAL;
    }
  }

  subdev->prepared = 1;
  return 0;
}


int startSubdevice( struct subdeviceT *subdev )
{ 
  int retVal = 0;

  if ( !subdev->prepared ) {
    ERROR_MSG( "startSubdevice ERROR: subdevice %i on device %s not prepared.\n",
	       subdev->subdev, devname );
    return -EBUSY;
  }

  if ( subdev->running ) {
    ERROR_MSG( "startSubdevice ERROR: subdevice %i on device %s already running.\n",
	       subdev->subdev, devname );
    return -EBUSY;
  }

  subdev->pending = 1;
  if ( !dynClampTask.running && subdev->type == SUBDEV_IN ) {
    // only ai can start the loop!
    dynClampTask.aoIndex = 0;
    dynClampTask.reqFreq = subdev->frequency;

    // start dynamic clamp task: 
    retVal = init_dynclamp_loop();
    if ( retVal < 0 ) {
      ERROR_MSG( "startSubdevice: failed to start dynamic clamp loop for subdevice %d!\n",
		 subdev->subdev );
      subdev->running = 0;
      return -ENOMEM;
    }
    DEBUG_MSG( "startSubdevice: successfully started dynclamp_loop!\n" );
  }

  subdev->running = 1;

  DEBUG_MSG( "startSubdevice: successfully started subdevice %d type %s!\n",
	     subdev->subdev, subdev->type == SUBDEV_IN ? "AI" : "AO" );

  return 0;
}


int stopSubdevice( struct subdeviceT *subdev, int kill )
{ 
  int i;
  int airunning = 0;

  DEBUG_MSG( "stopSubdevice: subdevice %d with kill=%d\n", subdev->subdev, kill );

  if ( !subdev->running )
    return 0;

  if ( kill && subdev->type == SUBDEV_IN ) {
    // stopping ai stops everything:
    stopSubdevice( &aosubdev, 0 );
  }

  airunning = aisubdev.running;

  if ( kill && airunning == 0 ) {
    DEBUG_MSG( "stopSubdevice: halt dynclamp task\n" );
    cleanup_dynclamp_loop();
  }

  // stop subdevice:
  for ( i = 0; i < subdev->chanN; i++ )
    subdev->chanlist[i].isUsed = 0;
  subdev->running = 0;

  return 0;
}


int setDigitalIO( struct dioIOCT *dioIOC )
{
  int subdevice = dioIOC->subdev;
  unsigned int bit = 0;
  int channel = 0;
  int direction = 0;
#ifdef ENABLE_TTLPULSE
  int pT = dioIOC->pulseType;
  int iT = 0;
  int k = 0;
  int found = 0;
#endif

  if ( dioIOC->op == DIO_CONFIGURE ) {
    if ( dioIOC->bitfield ) {
      bit = 1;
      for ( channel=0; channel<32; channel++ ) {
	if ( ( dioIOC->lines & bit ) > 0 ) {
	  direction = COMEDI_INPUT;
	  if ( ( dioIOC->output & bit ) > 0 )
	    direction = COMEDI_OUTPUT;
	  if ( comedi_dio_config( device, subdevice, channel, direction ) < 0 ) {
	    comedi_perror( "setDigitalIO() -> DIO_CONFIGURE" );
	    ERROR_MSG( "setDigitalIO: comedi_dio_config bitfield on device %s, subdevice %d, channel %d, direction %d failed!\n",
		       devname, subdevice, channel, direction );
	    return -EFAULT;
	  }
	}
	bit *= 2;
      }
    }
    else {
      direction = dioIOC->output ? COMEDI_OUTPUT : COMEDI_INPUT;
      if ( comedi_dio_config( device, subdevice, dioIOC->lines, direction ) < 0 ) {
	comedi_perror( "setDigitalIO() -> DIO_CONFIGURE" );
	ERROR_MSG( "setDigitalIO: comedi_dio_config single channel on device %s, subdevice %d, channel %d, direction %d failed!\n",
		   devname, subdevice, dioIOC->lines, direction );
	return -EFAULT;
      }
    }
  }
  else if ( dioIOC->op == DIO_READ ) {
    if ( dioIOC->bitfield ) {
      bit = 0;
      if ( comedi_dio_bitfield( device, subdevice, dioIOC->lines, &bit ) < 0 ) {
	comedi_perror( "setDigitalIO() -> DIO_READ" );
	ERROR_MSG( "setDigitalIO: comedi_dio_read on device %s subdevice %d failed!\n",
		  devname, subdevice );
	return -EFAULT;
      }
      dioIOC->output = bit & dioIOC->lines;
    }
    else {
      bit = 0;
      if ( comedi_dio_read( device, subdevice, dioIOC->lines, &bit ) != 1 ) {
	comedi_perror( "setDigitalIO() -> DIO_READ" );
	ERROR_MSG( "setDigitalIO: comedi_dio_read on device %s subdevice %d failed!\n",
		  devname, subdevice );
	return -EFAULT;
      }
      dioIOC->output = bit;
    }
  }
  else if ( dioIOC->op == DIO_WRITE ) {
    if ( dioIOC->bitfield ) {
      bit = dioIOC->output;
      if ( comedi_dio_bitfield( device, subdevice, dioIOC->lines, &bit ) < 0 ) {
	comedi_perror( "setDigitalIO() -> DIO_WRITE" );
	ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		  devname, subdevice );
	return -EFAULT;
      }
    }
    else {
      if ( comedi_dio_write( device, subdevice, dioIOC->lines, dioIOC->output ) != 1 ) {
	comedi_perror( "setDigitalIO() -> DIO_WRITE" );
	ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		  devname, subdevice );
	return -EFAULT;
      }
    }
  }
#ifdef ENABLE_TTLPULSE
  else if ( dioIOC->op == DIO_ADD_TTLPULSE ) {
    if ( pT < TTL_START_WRITE || pT >= MAXTTLPULSETYPES )
      return -EINVAL;
    for ( iT = 0; iT < MAXTTLPULSES && ttlInsns[pT][iT].n > 0; iT++ );
    if ( iT >= MAXTTLPULSES )
      return -ENOMEM;
    if ( comedi_dio_write( device, subdevice, dioIOC->lines, dioIOC->output ) != 1 ) {
      comedi_perror( "setDigitalIO() -> DIO_ADD_TTLPULSE" );
      ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		 devname, subdevice );
      return -EFAULT;
    }
    memset( &ttlInsns[pT][iT], 0, sizeof(comedi_insn) );
    ttlInsns[pT][iT].insn = INSN_WRITE;
    ttlInsns[pT][iT].n = 1;
    ttlInsns[pT][iT].data = ( dioIOC->output ? &ttlHigh : &ttlLow );
    ttlInsns[pT][iT].subdev = subdevice;
    ttlInsns[pT][iT].chanspec = CR_PACK( dioIOC->lines, 0, 0 );
    DEBUG_MSG( "setDigitalIO: add pulse pT=%d  iT=%d  output=%d subdev=%d lines=%d\n",
	       pT, iT, ttlInsns[pT][iT].data[0], ttlInsns[pT][iT].subdev,
	       ttlInsns[pT][iT].chanspec );
  }
  else if ( dioIOC->op == DIO_CLEAR_TTLPULSE ) {
    found = 0;
    for ( pT = 0; pT < MAXTTLPULSETYPES; pT++ ) {
      for ( iT = 0; iT < MAXTTLPULSES && ttlInsns[pT][iT].n > 0; ) {
	if ( ttlInsns[pT][iT].subdev == subdevice &&
	     ttlInsns[pT][iT].chanspec == CR_PACK( dioIOC->lines, 0, 0 ) ) {
	  found = 1;
	  ttlInsns[pT][iT].n = 0;
	  for ( k = iT+1; k < MAXTTLPULSES; k++ )
	    ttlInsns[pT][k-1] = ttlInsns[pT][k];
	}
	else
	  iT++;
      }
    }
    if ( found ) {
      if ( comedi_dio_write( device, subdevice, dioIOC->lines, dioIOC->output ) != 1 ) {
	comedi_perror( "setDigitalIO() -> DIO_CLEAR_TTLPULSE" );
	ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		   devname, subdevice );
	return -EFAULT;
      }
    }
  }
#endif
  else if ( dioIOC->op == DIO_SET_SYNCPULSE ) {
#ifdef ENABLE_SYNCSEC
    syncSECInsnLow.subdev = subdevice;
    syncSECInsnLow.chanspec = CR_PACK( dioIOC->lines, 0, 0 );
    syncSECInsnHigh.subdev = subdevice;
    syncSECInsnHigh.chanspec = CR_PACK( dioIOC->lines, 0, 0 );
    syncSECPulse = dioIOC->pulsewidth;
    if ( syncSECPulse <= 0 ) {
      ERROR_MSG( "setDigitalIO: syncSECPulse %d ns is not positive!\n", syncSECPulse );
      syncSECPulse = 20000;
      syncSECInsnLow.subdev = -1;
      syncSECInsnLow.chanspec = 0;
      syncSECInsnHigh.subdev = -1;
      syncSECInsnHigh.chanspec = 0;
      ERROR_MSG( "setDigitalIO: disabled syncSECPulse.\n" );
      return -EINVAL;
    }
    if ( comedi_do_insn( device, &syncSECInsnHigh ) != 1 ) {
      comedi_perror( "setDigitalIO() -> DIO_SET_SYNCPULSE" );
      ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		 devname, subdevice );
      syncSECInsnLow.subdev = -1;
      syncSECInsnLow.chanspec = 0;
      syncSECInsnHigh.subdev = -1;
      syncSECInsnHigh.chanspec = 0;
      ERROR_MSG( "setDigitalIO: disabled syncSECPulse.\n" );
      return -EFAULT;
    }
#else
    return -ENOTTY;
#endif
  }
  else if ( dioIOC->op == DIO_CLEAR_SYNCPULSE ) {
#ifdef ENABLE_SYNCSEC
    if ( syncSECInsnLow.subdev >= 0 ) {
      if ( comedi_do_insn( device, &syncSECInsnLow ) != 1 ) {
	comedi_perror( "setDigitalIO() -> DIO_SET_SYNCPULSE" );
	ERROR_MSG( "setDigitalIO: comedi_dio_write on device %s subdevice %d failed!\n",
		   devname, subdevice );
	return -EFAULT;
      }
    }
    syncSECInsnLow.subdev = -1;
    syncSECInsnLow.chanspec = 0;
    syncSECInsnHigh.subdev = -1;
    syncSECInsnHigh.chanspec = 0;
#else
    return -ENOTTY;
#endif
  }
  else
    return -EINVAL;
  return 0;
}


int setAnalogTrigger( struct triggerIOCT *triggerIOC )
{
#ifdef ENABLE_TRIGGER

  if ( device ) {
    if ( strcmp( devname, triggerIOC->devname ) != 0 ) {
      ERROR_MSG( "setAnalogTrigger: comedi device %s does not match %s of the module\n", 
		 triggerIOC->devname, devname );
      return -1;
    }
  }
  else {
    ERROR_MSG( "setAnalogTrigger: no comedi device is opened yet\n" );
    return -1;
  }

  // disable trigger:
  trigger.enabled = 0;

  // setup trigger parameter:
  trigger.subdev = triggerIOC->subdev;
  trigger.chan = triggerIOC->channel;
  trigger.alevel = triggerIOC->alevel;

  DEBUG_MSG( "setAnalogTrigger: setup trigger for channel %d on subdevice %d\n",
	     trigger.chan, trigger.subdev );

  // enable trigger:
  trigger.enabled = 1;
  return 0;
#else
  return -EINVAL;
#endif
}


int unsetAnalogTrigger( struct triggerIOCT *triggerIOC )
{
#ifdef ENABLE_TRIGGER
  int iC;

  // disable trigger:
  trigger.enabled = 0;
  for ( iC = 0; iC < aisubdev.chanN; iC++ )
    aisubdev.chanlist[iC].trigger = 0;
  for ( iC = 0; iC < aosubdev.chanN; iC++ )
    aosubdev.chanlist[iC].trigger = 0;

  return 0;
#else
  return -EINVAL;
#endif
}


///////////////////////////////////////////////////////////////////////////////
// *** REAL-TIME TASKS *** 
///////////////////////////////////////////////////////////////////////////////


static inline void sample_to_value( struct chanT *pChan )
{
  double term = 1.0;
  double sample = pChan->lsample - pChan->converter.expansion_origin;
  unsigned i;

  pChan->voltage = 0.0;
  for ( i=0; i <= pChan->converter.order; ++i ) {
    pChan->voltage += pChan->converter.coefficients[i] * term;
    term *= sample;
  }
  pChan->voltage *= pChan->scale;
}


static inline void value_to_sample( struct chanT *pChan, float value )
{
  double sample = 0.0;
  double term = 1.0;
  unsigned i;
  value *= pChan->scale;
  value -= pChan->converter.expansion_origin;
  for ( i=0; i <= pChan->converter.order; ++i ) {
    sample += pChan->converter.coefficients[i] * term;
    term *= value;
  }
  pChan->lsample = (lsampl_t)sample;
}


/*! Dynamic clamp task */
void dynclamp_loop( long dummy )
{
  int retVal;
  int iC;
#ifdef ENABLE_TTLPULSE
  int iT;
#endif
  struct chanT *pChan;
  float voltage;
#if defined(ENABLE_INTERVALS) || defined(ENABLE_SYNCSEC)
  RTIME currenttime = 0;
  RTIME newtime = 0;
  int difftime = 0;   // to avoid __divdi3 issues we use an int here
#endif
#if defined(ENABLE_AITIME) || defined(ENABLE_AOTIME) || defined(ENABLE_MODELTIME)
  RTIME starttime = 0;
  RTIME stoptime = 0;
  int dtime = 0;   // to avoid __divdi3 issues we use an int here
#endif
#if defined(ENABLE_AIACQUISITIONTIME) || defined(ENABLE_AICONVERSIONTIME)
  RTIME startsampletime = 0;
  RTIME stopsampletime = 0;
  int dsampletime = 0;   // to avoid __divdi3 issues we use an int here
#endif
  int triggerevs[5] = { 1, 0, 0, 0, 0 };
  int prevtriggerevs[5] = { 0, 0, 0, 0, 0 };
#ifdef ENABLE_SYNCSEC
  float currentfac = 1.0;
#endif

  DEBUG_MSG( "dynclamp_loop: starting dynamic clamp loop at %u Hz\n", 
	      1000000000/dynClampTask.periodLengthNs );

  dynClampTask.loopCnt = 0;
  dynClampTask.aoIndex = -1;
  dynClampTask.running = 1;

#if defined(ENABLE_INTERVALS) || defined(ENABLE_SYNCSEC)
  currenttime = rt_get_cpu_time_ns();
  difftime = dynClampTask.periodLengthNs;
  statusInput[intervalstatusinx] = 1e-9*difftime;
#endif
#ifdef ENABLE_AITIME
  statusInput[aitimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AIACQUISITIONTIME
  statusInput[aiacquisitiontimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AICONVERSIONTIME
  statusInput[aiconversiontimestatusinx] = 0.0;
#endif
#ifdef ENABLE_AOTIME
  statusInput[aotimestatusinx] = 0.0;
#endif
#ifdef ENABLE_MODELTIME
  statusInput[modeltimestatusinx] = 0.0;
#endif

#ifdef ENABLE_COMPUTATION
  // initialize model-specific variables:
  initModel();
#endif

  /* Somehow the first time this function waits for nothing... */
  rt_task_wait_period();
  
  /**************************************************************************/
  /******** LOOP START: *****************************************************/
  /**************************************************************************/
  while( aisubdev.running ) {

#ifdef ENABLE_TTLPULSE
    for ( iT = 0; iT < MAXTTLPULSES && ttlStartWriteInsn[iT].n > 0; iT++ ) {
      retVal = comedi_do_insn( device, &ttlStartWriteInsn[iT] );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at start write: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at start write\n", iT );
      }
    }
#endif

#ifdef ENABLE_SYNCSEC
    if ( syncSECPulse > 0 )
      currentfac = difftime / syncSECPulse;
    else
      currentfac = 1.0;
#endif

    /******** WRITE TO ANALOG OUTPUT: ******************************************/
    /****************************************************************************/
#ifdef ENABLE_AOTIME
    starttime = rt_get_cpu_time_ns();
#endif

    if ( aosubdev.running ) {

      // check for pending start trigger:
      if ( aosubdev.pending ) {
	DEBUG_MSG( "dynclamp_loop: REALTIMELOOP PENDING AO startsrc=%d, prevtriger1=%d, triger1=%d, pv=%d, v=%d\n",
		   aosubdev.startsource, prevtriggerevs[1], triggerevs[1],
		   (int)(100.0*aisubdev.chanlist[0].prevvoltage), (int)(100.0*aisubdev.chanlist[0].voltage) );
	if ( triggerevs[aosubdev.startsource] &&
	     ! prevtriggerevs[aosubdev.startsource] ) {
	  DEBUG_MSG( "dynclamp_loop: REALTIMELOOP PENDING AO SETUP duration=%lu, loopCnt=%lu\n",
		     aosubdev.duration, dynClampTask.loopCnt );
	  aosubdev.delay = dynClampTask.loopCnt + aosubdev.delay; 
	  aosubdev.duration = aosubdev.delay + aosubdev.duration;
	  dynClampTask.aoIndex = aosubdev.delay;
	  aosubdev.pending = 0;
	  DEBUG_MSG( "dynclamp_loop: START PENDING AO duration=%lu delay=%lu, loopCnt=%lu\n",
		     aosubdev.duration, aosubdev.delay, dynClampTask.loopCnt );
	}
      }

      if (  ! aosubdev.pending ) {
	// check end of stimulus:
	if ( !aosubdev.continuous &&
	     aosubdev.duration <= dynClampTask.loopCnt ) {
	  DEBUG_MSG( "dynclamp_loop: finished ao subdevice at loop %lu\n", dynClampTask.loopCnt );
	  rtf_reset( aosubdev.fifo );
	  stopSubdevice( &aosubdev, /*kill=*/0 );
#ifdef ENABLE_TTLPULSE
	  for ( iT = 0; iT < MAXTTLPULSES && ttlEndAOInsn[iT].n > 0; iT++ ) {
	    retVal = comedi_do_insn( device, &ttlEndAOInsn[iT] );
	    if ( retVal < 1 ) {
	      if ( retVal < 0 )
		comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at end ao: comedi_do_insn" );
	      ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at end ao\n", iT );
	    }
	  }
#endif
	}
	else if ( dynClampTask.loopCnt >= aosubdev.delay ) {
#ifdef ENABLE_TTLPULSE
	  // start of stimulus:
	  if ( dynClampTask.loopCnt == aosubdev.delay ) {
	    for ( iT = 0; iT < MAXTTLPULSES && ttlStartAOInsn[iT].n > 0; iT++ ) {
	      retVal = comedi_do_insn( device, &ttlStartAOInsn[iT] );
	      if ( retVal < 1 ) {
		if ( retVal < 0 )
		  comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at start ao: comedi_do_insn" );
		ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at start ao\n", iT );
	      }
	    }
	  }
#endif
	  // read output from FIFO:
	  for ( iC = 0; iC < aosubdev.chanN; iC++ ) {
	    pChan = &aosubdev.chanlist[iC];
	    if ( pChan->isUsed ) {
	      // get data from FIFO:
	      retVal = rtf_get( aosubdev.fifo, &pChan->voltage, sizeof(float) );
	      if ( retVal != sizeof(float) ) {
		if ( retVal == EINVAL ) {
		  ERROR_MSG( "dynclamp_loop: ERROR! No open FIFO for AO subdevice at loopCnt %lu\n", dynClampTask.loopCnt );
		  ERROR_MSG( "dynclamp_loop: Stop dynClampTask." );
		  dynClampTask.running = 0;
		  dynClampTask.duration = 0;
		  return;
		}
		aosubdev.error = E_UNDERRUN;
		ERROR_MSG( "dynclamp_loop: ERROR! Data buffer underrun for AO subdevice at loopCnt %lu\n", dynClampTask.loopCnt );
		aosubdev.running = 0;
		continue;
	      }
#ifdef ENABLE_COMPUTATION
	      if ( pChan->param > 0 ) {
		paramOutput[pChan->chan] = pChan->voltage;
	      }
#endif
	    }
	  }
	}

      }  // ! aosubdev.pending
    }  // aosubdev.running
	
    // write output to daq board:
    for ( iC = 0; iC < aosubdev.chanN; iC++ ) {
      pChan = &aosubdev.chanlist[iC];
      // this is an output to the DAQ board:
#ifdef ENABLE_COMPUTATION
      if ( pChan->param == 0 ) {
#endif
	voltage = pChan->voltage;

#ifdef ENABLE_COMPUTATION
	// add model output to sample:
	if ( pChan->modelIndex >= 0 ) {
	  statusInput[pChan->statusIndex] = voltage;
	  statusInput[pChan->statusIndex+1] = output[pChan->modelIndex];
	  voltage += output[pChan->modelIndex];
	  statusInput[pChan->statusIndex+2] = voltage;
#ifdef ENABLE_SYNCSEC
	  statusInput[pChan->statusIndex+3] = voltage * currentfac;
#endif
	}
#endif
	// write out Sample:
#ifdef ENABLE_SYNCSEC
	voltage *= currentfac;
#endif
	value_to_sample( pChan, voltage ); // sets pChan->lsample
	retVal = comedi_do_insn( device, &pChan->insn );
	if ( retVal < 1 ) {
	  aosubdev.running = 0;
	  aosubdev.error = E_NODATA;
	  ERROR_MSG( "dynclamp_loop: ERROR! failed to write data to AO subdevice channel %d at loopCnt %lu\n",
		     iC, dynClampTask.loopCnt );
	  if ( retVal < 0 ) {
	    comedi_perror( "dynclampmodule: dynclamp_loop: comedi_data_write" );
	    aosubdev.error = E_COMEDI;
	    ERROR_MSG( "dynclamp_loop: ERROR! failed to write to AO subdevice channel %d at loopCnt %lu\n",
		       iC, dynClampTask.loopCnt );
	  }
	}
#ifdef ENABLE_COMPUTATION
      }
#endif
    } // end of ao channel loop
#ifdef ENABLE_AOTIME
    stoptime = rt_get_cpu_time_ns();
    dtime = stoptime - starttime;
    statusInput[aotimestatusinx] = 1e-9*dtime;
#endif


#ifdef ENABLE_TTLPULSE
    for ( iT = 0; iT < MAXTTLPULSES && ttlEndWriteInsn[iT].n > 0; iT++ ) {
      retVal = comedi_do_insn( device, &ttlEndWriteInsn[iT] );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at end write: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at end write\n", iT );
      }
    }
#endif


#ifdef ENABLE_SYNCSEC
    if ( syncSECInsnHigh.subdev >= 0 ) {
      retVal = comedi_do_insn( device, &syncSECInsnHigh );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop seting DIO high at start write for syncing SEC: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to set DIO high at start write for syncing SEC\n" );
      }
    }

#else

    /******** SLEEP FOR NEURON TO REACT TO GIVEN OUTPUT: ************************/
    /****************************************************************************/
    // PROBLEM: rt_sleep is timed using jiffies only (granularity = 1msec)
	// int retValSleep = rt_sleep( nano2count( INJECT_RECORD_DELAY ) );
    rt_busy_sleep( INJECT_RECORD_DELAY );

#endif

#ifdef ENABLE_TTLPULSE
    for ( iT = 0; iT < MAXTTLPULSES && ttlStartReadInsn[iT].n > 0; iT++ ) {
      retVal = comedi_do_insn( device, &ttlStartReadInsn[iT] );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at start read: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at start read\n", iT );
      }
    }
#endif
    
    /******** FROM ANALOG INPUT: **********************************************/
    /****************************************************************************/
#ifdef ENABLE_AITIME
    starttime = rt_get_cpu_time_ns();
#endif
    // ai is always running!
    if ( aisubdev.pending ) {
      if ( triggerevs[aisubdev.startsource] &&
	   ! prevtriggerevs[aisubdev.startsource] ) {
	aisubdev.delay = dynClampTask.loopCnt + aisubdev.delay; 
	aisubdev.duration = aisubdev.delay + aisubdev.duration;
	aisubdev.pending = 0;
      }
    }
          
    if ( ! aisubdev.pending ) {
      // check duration:
      if ( !aisubdev.continuous &&
	   aisubdev.chanN > 0 &&
	   aisubdev.duration <= dynClampTask.loopCnt ) {
	stopSubdevice( &aisubdev, /*kill=*/1 );
      }

      // for every ai channel:
      for ( iC = 0; iC < aisubdev.chanN; iC++ ) {

	pChan = &aisubdev.chanlist[iC];

	// previous sample:
	pChan->prevvoltage = pChan->voltage;

	// acquire sample:
	if ( pChan->param == 0 ) {
#ifdef ENABLE_AIACQUISITIONTIME
	  startsampletime = rt_get_cpu_time_ns();
#endif
	  retVal = comedi_do_insn( device, &pChan->insn );     
#ifdef ENABLE_AIACQUISITIONTIME
	  stopsampletime = rt_get_cpu_time_ns();
	  dsampletime = stopsampletime - startsampletime;
	  statusInput[aiacquisitiontimestatusinx] = 1e-9*dsampletime;
#endif
	  if ( retVal < 1 ) {
	    aisubdev.running = 0;
	    aisubdev.error = E_NODATA;
	    ERROR_MSG( "dynclamp_loop: ERROR! failed to read data from AI subdevice channel %d at loopCnt %lu\n",
		       iC, dynClampTask.loopCnt );
	    if ( retVal < 0 ) {
	      comedi_perror( "dynclampmodule: dynclamp_loop: comedi_data_read" );
	      aisubdev.error = E_COMEDI;
	      ERROR_MSG( "dynclamp_loop: ERROR! failed to read from AI subdevice channel %d at loopCnt %lu\n",
			 iC, dynClampTask.loopCnt );
	      continue;
	    }
	  }
	  // convert to voltage:
#ifdef ENABLE_AICONVERSIONTIME
	  startsampletime = rt_get_cpu_time_ns();
#endif
	  sample_to_value( pChan ); // sets pChan->voltage from pChan->lsample
	  if ( pChan->modelIndex >= 0 )
	    input[pChan->modelIndex] = pChan->voltage;
#ifdef ENABLE_AICONVERSIONTIME
	  stopsampletime = rt_get_cpu_time_ns();
	  dsampletime = stopsampletime - startsampletime;
	  statusInput[aiconversiontimestatusinx] = 1e-9*dsampletime;
#endif
	}
	else {
	  if ( pChan->param == 1 )
	    pChan->voltage = paramInput[pChan->chan]*pChan->scale;
	  else
	    pChan->voltage = statusInput[pChan->chan]*pChan->scale;
	}
	  
#ifdef RTMODULE_DEBUG
	if ( aisubdev.running == 0 )
	  ERROR_MSG( "dynclamp_loop: ERROR! ai subdevice somehow not running\n" );
#endif
	// write to FIFO:
	retVal = rtf_put( aisubdev.fifo, &pChan->voltage, sizeof(float) );
#ifdef RTMODULE_DEBUG
	if ( aisubdev.running == 0 )
	  ERROR_MSG( "dynclamp_loop: ERROR! rtf_put turned ai subdevice not running\n" );
#endif

	if ( retVal != sizeof(float) ) {
	  ERROR_MSG( "dynclamp_loop: ERROR! rtf_put failed, return value=%d\n", retVal );
	  rtf_reset( aisubdev.fifo );
	  aisubdev.running = 0;
	  dynClampTask.running = 0;
	  dynClampTask.duration = 0;
	  if ( retVal == EINVAL ) {
	    ERROR_MSG( "dynclamp_loop: ERROR! No open FIFO for AI subdevice at loopCnt %lu\n", dynClampTask.loopCnt );
	    ERROR_MSG( "dynclamp_loop: stop dynClampTask." );
	    return;
	  }
	  aisubdev.error = E_OVERFLOW;
	  ERROR_MSG( "dynclamp_loop: ERROR! FIFO buffer overflow for AI subdevice at loopCnt %lu\n",
		     dynClampTask.loopCnt );
	  ERROR_MSG( "dynclamp_loop: stop dynClampTask." );
	  return;
	}

#ifdef RTMODULE_DEBUG
	if ( aisubdev.running == 0 )
	  ERROR_MSG( "dynclamp_loop: ERROR! rtf_put error handling turned ai subdevice not running\n" );
#endif

#ifdef ENABLE_TRIGGER
	// trigger:
	if ( pChan->trigger ) {
	  prevtriggerevs[1] = triggerevs[1];
	  if ( pChan->voltage > pChan->alevel && pChan->prevvoltage <= pChan->alevel ) {
	    triggerevs[1] = 1;
	  }
	  else if ( pChan->voltage < pChan->alevel && pChan->prevvoltage >= pChan->alevel ) {
	    triggerevs[1] = 0;
	  }
	}
#endif
	  
      } // end of channel loop
    } // ! pending
#ifdef ENABLE_AITIME
    stoptime = rt_get_cpu_time_ns();
    dtime = stoptime - starttime;
    statusInput[aitimestatusinx] = 1e-9*dtime;
#endif

#ifdef ENABLE_SYNCSEC
    if ( syncSECInsnLow.subdev >= 0 ) {
      retVal = comedi_do_insn( device, &syncSECInsnLow );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop seting DIO low at start write for syncing SEC: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to set DIO low at start write for syncing SEC\n" );
      }
    }
#endif

#ifdef ENABLE_TTLPULSE
    for ( iT = 0; iT < MAXTTLPULSES && ttlEndReadInsn[iT].n > 0; iT++ ) {
      retVal = comedi_do_insn( device, &ttlEndReadInsn[iT] );
      if ( retVal < 1 ) {
	if ( retVal < 0 )
	  comedi_perror( "dynclampmodule: dynclamp_loop ttl pulse at end read: comedi_do_insn" );
	ERROR_MSG( "dynclamp_loop: ERROR! failed to write TTL pulse %d at end read\n", iT );
      }
    }
#endif


    /****************************************************************************/
#ifdef ENABLE_MODELTIME
    starttime = rt_get_cpu_time_ns();
#endif
#ifdef ENABLE_COMPUTATION
    computeModel();
#endif
#ifdef ENABLE_MODELTIME
    stoptime = rt_get_cpu_time_ns();
    dtime = stoptime - starttime;
    statusInput[modeltimestatusinx] = 1e-9*dtime;
#endif

    /******** WAIT FOR CALCULATION TASK TO COMPUTE RESULT: **********************/
    /****************************************************************************/
    dynClampTask.loopCnt++;

    //    start = rt_get_cpu_time_ns();
    rt_task_wait_period();

#if defined(ENABLE_INTERVALS) || defined(ENABLE_SYNCSEC)
    newtime = rt_get_cpu_time_ns();
    difftime = newtime - currenttime;
    currenttime = newtime;
    statusInput[intervalstatusinx] = 1e-9*difftime;
#endif

  } // END OF DYNCLAMP LOOP
    
  dynClampTask.running = 0;
  dynClampTask.duration = 0;

  DEBUG_MSG( "dynclamp_loop: left dynamic clamp loop after %lu cycles\n",
	     dynClampTask.loopCnt );
}


///////////////////////////////////////////////////////////////////////////////
// *** RTAI FUNCTIONS ***
///////////////////////////////////////////////////////////////////////////////


int init_dynclamp_loop( void )
{
  int stackSize = 32768;
  int priority;
  int usesFPU = 1;   /* we need FPU support in any case! */
  void* signal = NULL;
  int dummy = 23;
  int retVal;
  RTIME periodTicks;

  DEBUG_MSG( "init_dynclamp_loop: Trying to initialize dynamic clamp RTAI task...\n" );

#ifndef CONFIG_RTAI_FPU_SUPPORT
  #error "RTAI FPU support is not enabled. Reconfigure, compile and install RTAI kernel modules."
#endif

  // test if dynamic clamp frequency is valid:
  if ( dynClampTask.reqFreq <= 0 || dynClampTask.reqFreq > MAX_FREQUENCY ) {
    ERROR_MSG( "init_dynclamp_loop ERROR: %dHz -> invalid dynamic clamp frequency. Valid range is 1 .. %dHz\n", 
	       dynClampTask.reqFreq, MAX_FREQUENCY );
    return -1;
  }

  // initializing rt-task for dynamic clamp with high priority:
  priority = RT_SCHED_HIGHEST_PRIORITY;
  rt_linux_use_fpu( usesFPU );      /* declare if we use the FPU */
  retVal = rt_task_init( &dynClampTask.rtTask, dynclamp_loop, dummy, stackSize, 
			 priority, usesFPU, signal );
  if ( retVal ) {
    ERROR_MSG( "init_dynclamp_loop ERROR: failed to initialize real-time task for dynamic clamp! stacksize was set to %d bytes.\n", 
	       stackSize );
    return -1;
  }
  DEBUG_MSG( "init_dynclamp_loop: initialized dynamic clamp RTAI task. Trying to make it periodic...\n" );

    // START rt-task for dynamic clamp as periodic:
  periodTicks = start_rt_timer( nano2count( 1000000000/dynClampTask.reqFreq ) );  
  dynClampTask.periodLengthNs = count2nano( periodTicks );
  dynClampTask.setFreq = 1000000000 / dynClampTask.periodLengthNs;
#ifdef ENABLE_COMPUTATION
  loopInterval = 1.0e-9*dynClampTask.periodLengthNs;
  loopRate = 1.0e9/dynClampTask.periodLengthNs;
#endif
  if ( rt_task_make_periodic( &dynClampTask.rtTask, rt_get_time(), periodTicks ) 
      != 0 ) {
    printk( "init_dynclamp_loop ERROR: failed to start periodic real-time task for data acquisition! loading of module failed!\n" );
    return -3;
  }
  INFO_MSG( "init_dynclamp_loop: periodic task successfully started... requested freq: %d , accepted freq: ~%u (period=%uns)\n", 
	    dynClampTask.reqFreq, dynClampTask.setFreq, dynClampTask.periodLengthNs );

  // For now, the DynClampTask shall always run until any subdev is stopped:
  dynClampTask.continuous = 1;

  return 0;
}


void cleanup_dynclamp_loop( void )
{
  stop_rt_timer();
  rt_task_delete( &dynClampTask.rtTask );
  memset( &dynClampTask, 0, sizeof(struct dynClampTaskT) );
  INFO_MSG( "cleanup_dynclamp_loop: stopped periodic task\n" );
}


///////////////////////////////////////////////////////////////////////////////
// *** IOCTL ***
///////////////////////////////////////////////////////////////////////////////

#ifdef HAVE_UNLOCKED_IOCTL
long dynclampmodule_unlocked_ioctl( struct file *fModule, unsigned int cmd,
				    unsigned long arg )
#else
int dynclampmodule_ioctl( struct inode *devFile, struct file *fModule, 
			  unsigned int cmd, unsigned long arg )
#endif
{
  static struct deviceIOCT deviceIOC;
  static struct chanlistIOCT chanlistIOC;
  static struct syncCmdIOCT syncCmdIOC;
#ifdef ENABLE_COMPUTATION
  static struct traceInfoIOCT traceInfo;
  static struct traceChannelIOCT traceChannel;
#endif
  static struct dioIOCT dioIOC;
  static struct triggerIOCT triggerIOC;

  enum subdevTypes subdevtype;
  int retVal = 0;
  int rc = 0;
  int tmp;
  int running;
  unsigned long luTmp;


  if ( _IOC_TYPE(cmd) != RTMODULE_MAJOR || _IOC_NR(cmd) > RTMODULE_IOC_MAXNR) {
    ERROR_MSG( "ioctl: Major wrong or ioctl %d bigger than max %d\n", 
	       _IOC_TYPE(cmd), RTMODULE_IOC_MAXNR );
    return -ENOTTY;
  }
  DEBUG_MSG( "dynclampmodule_ioctl: user triggered ioctl %d %s\n",
	     _IOC_NR( cmd ), iocNames[_IOC_NR( cmd )] );

  mutex_lock( &mutex );

  switch( cmd ) {
    

    /******** GIVE INFORMATION TO USER SPACE: ***********************************/
    
  case IOC_GETRATE:
    tmp = dynClampTask.setFreq;
    retVal = put_user( tmp, (int __user *)arg );
    rc = retVal == 0 ? 0 : -EFAULT;
    break;

  case IOC_GETAOINDEX:
    luTmp = dynClampTask.aoIndex;
    if ( luTmp < 0 ) {
      rc = -ENOSPC;
      break;
    }
    retVal = put_user( luTmp, (unsigned long __user *)arg );
    rc = retVal == 0 ? 0 : -EFAULT;
    break;

  case IOC_GETLOOPCNT:
    luTmp = dynClampTask.loopCnt;
    if ( luTmp < 0 ) {
      rc = -ENOSPC;
      break;
    }
    retVal = put_user( luTmp, (unsigned long __user *)arg );
    rc = retVal == 0 ? 0 : -EFAULT;
    break;

    /******** SET UP COMEDI: ****************************************************/

  case IOC_OPEN_SUBDEV:
    retVal = copy_from_user( &deviceIOC, (void __user *)arg, sizeof(struct deviceIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to deviceIOCT-struct for reading!\n" );
      rc = -EFAULT;
      break;
    }
    rc = openComediDevice( &deviceIOC );
    retVal = copy_to_user( (void __user *)arg, &deviceIOC, sizeof(struct deviceIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to deviceIOCT-struct for writing!\n" );
      rc = -EFAULT;
      break;
    }
    break;

  case IOC_REQ_CLOSE:
    if ( reqCloseSubdev >= 0 ) {
      ERROR_MSG( "ioctl IOC_REQ_CLOSE ERROR: Another close-request in progress with id %d!\n",
		 reqCloseSubdev );
      rc = -EAGAIN;
      break;
    }
    reqCloseSubdev = (int)arg;
    rc = 0;
    break;

  case IOC_CHANLIST:
    retVal = copy_from_user( &chanlistIOC, (void __user *)arg, sizeof(struct chanlistIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to chanlistIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    if ( chanlistIOC.type == SUBDEV_IN )
      rc = loadChanList( &chanlistIOC, &aisubdev );
    else if ( chanlistIOC.type == SUBDEV_OUT )
      rc = loadChanList( &chanlistIOC, &aosubdev );
    else
      rc = -EFAULT;
    break;

  case IOC_SYNC_CMD:
    retVal = copy_from_user( &syncCmdIOC, (void __user *)arg, sizeof(struct syncCmdIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to syncCmdIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    if ( syncCmdIOC.type == SUBDEV_IN )
      rc = loadSyncCmd( &syncCmdIOC, &aisubdev );
    else if ( syncCmdIOC.type == SUBDEV_OUT )
      rc = loadSyncCmd( &syncCmdIOC, &aosubdev );
    else
      rc = -EFAULT;
    break;


  case IOC_GET_TRACE_INFO:
    retVal = copy_from_user( &traceInfo, (void __user *)arg, sizeof(struct traceInfoIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid user pointer for traceInfoIOCT!\n" );
      rc = -EFAULT;
      break;
    }
    traceInfo.value = 0.0;
    rc = 0;
    switch( traceInfo.traceType ) {
#ifdef ENABLE_COMPUTATION
    case TRACE_IN:
      if ( traceIndex >= INPUT_N ) {
	traceIndex = 0;
	rc = -ERANGE; // signal end of list
	break;
      }
      strncpy( traceInfo.name, inputNames[traceIndex], PARAM_NAME_MAXLEN );
      strncpy( traceInfo.unit, inputUnits[traceIndex], PARAM_NAME_MAXLEN );
      DEBUG_MSG( "ioctl: input trace %s [%s]\n", traceInfo.name, traceInfo.unit );
      break;
    case TRACE_OUT:
      if ( traceIndex >= OUTPUT_N ) {
	traceIndex = 0;
	rc = -ERANGE; // signal end of list
	break;
      }
      strncpy( traceInfo.name, outputNames[traceIndex], PARAM_NAME_MAXLEN );
      strncpy( traceInfo.unit, outputUnits[traceIndex], PARAM_NAME_MAXLEN );
      traceInfo.value = output[traceIndex];
      DEBUG_MSG( "ioctl: output trace %s [%s]\n", traceInfo.name, traceInfo.unit );
      break;
    case PARAM_IN:
      if ( traceIndex >= PARAMINPUT_N ) {
	traceIndex = 0;
	rc = -ERANGE; // signal end of list
	break;
      }
      strncpy( traceInfo.name, paramInputNames[traceIndex], PARAM_NAME_MAXLEN );
      strncpy( traceInfo.unit, paramInputUnits[traceIndex], PARAM_NAME_MAXLEN );
      DEBUG_MSG( "ioctl: parameter input trace %s [%s]\n", traceInfo.name, traceInfo.unit );
      break;
    case PARAM_OUT:
      if ( traceIndex >= PARAMOUTPUT_N ) {
	traceIndex = 0;
	rc = -ERANGE; // signal end of list
	break;
      }
      strncpy( traceInfo.name, paramOutputNames[traceIndex], PARAM_NAME_MAXLEN );
      strncpy( traceInfo.unit, paramOutputUnits[traceIndex], PARAM_NAME_MAXLEN );
      traceInfo.value = paramOutput[traceIndex];
      DEBUG_MSG( "ioctl: parameter output trace %s [%s]\n", traceInfo.name, traceInfo.unit );
      break;
#endif
    case STATUS_IN:
      if ( traceIndex >= statusInputN ) {
	traceIndex = 0;
	rc = -ERANGE; // signal end of list
	break;
      }
      strncpy( traceInfo.name, statusInputNames[traceIndex], PARAM_NAME_MAXLEN );
      strncpy( traceInfo.unit, statusInputUnits[traceIndex], PARAM_NAME_MAXLEN );
      DEBUG_MSG( "ioctl: status input trace %s [%s]\n", traceInfo.name, traceInfo.unit );
      break;
    default: ;
      rc = -ERANGE; // signal end of list
    }
    if ( rc != 0 )
      break;
    retVal = copy_to_user( (void __user *)arg, &traceInfo, sizeof(struct traceInfoIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid user pointer for traceInfoIOCT!\n" );
      rc = -EFAULT;
      break;
    }
    traceIndex++;
    rc = 0;
    break;

  case IOC_SET_TRACE_CHANNEL:
#ifdef ENABLE_COMPUTATION
    retVal = copy_from_user( &traceChannel, (void __user *)arg, sizeof(struct traceChannelIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid user pointer for traceChannelIOCT!\n" );
      rc = -EFAULT;
      break;
    }
    switch( traceChannel.traceType ) {
    case TRACE_IN:
      inputChannels[chanIndex] = traceChannel.channel;
      DEBUG_MSG( "ioctl: input channel set to %d\n", traceChannel.channel );
      break;
    case TRACE_OUT:
      outputChannels[chanIndex] = traceChannel.channel;
      DEBUG_MSG( "ioctl: output channel set to %d\n", traceChannel.channel );
      break;
    default: ;
    }
    chanIndex++;
    if ( chanIndex >= INPUT_N )
      chanIndex = 0;
    rc = 0;
    break;
#else
    rc = -EFAULT; // Nothing done
    break;
#endif


  case IOC_START_SUBDEV:
    subdevtype = (enum subdevTypes)arg;
    if ( subdevtype == SUBDEV_IN )
      rc = startSubdevice( &aisubdev );
    else if ( subdevtype == SUBDEV_OUT )
      rc = startSubdevice( &aosubdev );
    else
      rc = -EFAULT;
    break;

  case IOC_STOP_SUBDEV:
    subdevtype = (enum subdevTypes)arg;
    if ( subdevtype == SUBDEV_IN )
      rc = stopSubdevice( &aisubdev, /*kill=*/1 );
    else if ( subdevtype == SUBDEV_OUT )
      rc = stopSubdevice( &aosubdev, /*kill=*/1 );
    else
      rc = -EFAULT;
    break;


  case IOC_CHK_RUNNING:
    retVal = get_user( tmp, (int __user *)arg );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to subdevice ID for running-query!" );
      rc = -EFAULT;
      break;
    }
    running = 0;
    if ( tmp == SUBDEV_IN )
      running = aisubdev.running;
    else if ( tmp == SUBDEV_OUT )
      running = aosubdev.running;
    else {
      ERROR_MSG( "ioctl ERROR: invalid subdevice type for running-query!\n" );
      rc = -EFAULT;
      break;
    }
    DEBUG_MSG( "ioctl: running = %d for subdev %s\n", running, tmp == SUBDEV_IN ? "AI" : "AO" );
    retVal = put_user( running, (int __user *)arg );
    rc = retVal == 0 ? 0 : -EFAULT;
    break;


    // ******* Digital IO: ********************************************
  case IOC_DIO_CMD:
    retVal = copy_from_user( &dioIOC, (void __user *)arg, sizeof(struct dioIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to dioIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    retVal = setDigitalIO( &dioIOC );
    if ( retVal != 0 ) {
      rc = retVal;
      break;
    }
    retVal = copy_to_user( (void __user *)arg, &dioIOC, sizeof(struct dioIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to dioIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    rc = 0;
    break;

    // ******* Trigger: ***********************************************

  case IOC_SET_TRIGGER:
    retVal = copy_from_user( &triggerIOC, (void __user *)arg, sizeof(struct triggerIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to triggerIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    rc = setAnalogTrigger( &triggerIOC );
    break;

  case IOC_UNSET_TRIGGER:
    retVal = copy_from_user( &triggerIOC, (void __user *)arg, sizeof(struct triggerIOCT) );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to triggerIOCT-struct!\n" );
      rc = -EFAULT;
      break;
    }
    rc = unsetAnalogTrigger( &triggerIOC );
    break;


#ifdef ENABLE_COMPUTATION
#ifdef ENABLE_LOOKUPTABLES
    // ******* Lookup tables: ***********************************************

  case IOC_SET_LOOKUP_K:
    retVal = get_user( lookupinx, (int __user *)arg );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to lookup index!" );
      lookupinx = -1;
      rc = -EFAULT;
      break;
    }
    if ( lookupinx < 0 || lookupinx >= MAXLOOKUPTABLES ) {
      ERROR_MSG( "ioctl ERROR: invalid lookup index!" );
      lookupinx = -1;
      rc = -EINVAL;
      break;
    }
    lookupn[lookupinx] = 0;
    if ( lookupx[lookupinx] != NULL )
      kfree( lookupx[lookupinx] );
    if ( lookupy[lookupinx] != NULL )
      kfree( lookupy[lookupinx] );
    lookupx[lookupinx] = NULL;
    lookupy[lookupinx] = NULL;
    break;

  case IOC_SET_LOOKUP_N:
    if ( lookupinx < 0 ) {
      ERROR_MSG( "ioctl ERROR: invalid lookup index!" );
      rc = -EINVAL;
      break;
    }
    retVal = get_user( lookupn[lookupinx], (int __user *)arg );
    if ( retVal ) {
      ERROR_MSG( "ioctl ERROR: invalid pointer to size of lookup table!" );
      lookupn[lookupinx] = 0;
      rc = -EFAULT;
    }
    break;

  case IOC_SET_LOOKUP_X:
    if ( lookupinx < 0 ) {
      ERROR_MSG( "ioctl ERROR: invalid lookup index!" );
      rc = -EINVAL;
      break;
    }
    if ( lookupx[lookupinx] != NULL ) {
      kfree( lookupx[lookupinx] );
      lookupx[lookupinx] = NULL;
    }
    if ( lookupn[lookupinx] > 0 ) {
      lookupx[lookupinx] = kmalloc( lookupn[lookupinx]*sizeof(float), GFP_KERNEL );
      if ( lookupx[lookupinx] == NULL ) {
	ERROR_MSG( "ioctl ERROR: failed to allocate memory for x-array of lookup table!\n" );
	rc = -ENOMEM;
      }
      else {
	retVal = copy_from_user( lookupx[lookupinx], (void __user *)arg,
				 lookupn[lookupinx]*sizeof(float) );
	if ( retVal ) {
	  ERROR_MSG( "ioctl ERROR: invalid pointer to x-array of lookup table!\n" );
	  rc = -EFAULT;
	}
      }
      if ( rc != 0 ) {
	if ( lookupx[lookupinx] != NULL ) {
	  kfree( lookupx[lookupinx] );
	  lookupx[lookupinx] = NULL;
	}
	if ( lookupy[lookupinx] != NULL ) {
	  kfree( lookupy[lookupinx] );
	  lookupy[lookupinx] = NULL;
	}
	lookupn[lookupinx] = 0;
      }
    }
    break;

  case IOC_SET_LOOKUP_Y:
    if ( lookupinx < 0 ) {
      ERROR_MSG( "ioctl ERROR: invalid lookup index!" );
      rc = -EINVAL;
      break;
    }
    if ( lookupy[lookupinx] != NULL ) {
      kfree( lookupy[lookupinx] );
      lookupy[lookupinx] = NULL;
    }
    if ( lookupn[lookupinx] > 0 ) {
      lookupy[lookupinx] = kmalloc( lookupn[lookupinx]*sizeof(float), GFP_KERNEL );
      if ( lookupy[lookupinx] == NULL ) {
	ERROR_MSG( "ioctl ERROR: failed to allocate memory for y-array of lookup table!\n" );
	rc = -ENOMEM;
      }
      else {
	retVal = copy_from_user( lookupy[lookupinx], (void __user *)arg,
				 lookupn[lookupinx]*sizeof(float) );
	if ( retVal ) {
	  ERROR_MSG( "ioctl ERROR: invalid pointer to y-array of lookup table!\n" );
	  rc = -EFAULT;
	}
      }
      if ( rc != 0 ) {
	if ( lookupx[lookupinx] != NULL ) {
	  kfree( lookupx[lookupinx] );
	  lookupx[lookupinx] = NULL;
	}
	if ( lookupy[lookupinx] != NULL ) {
	  kfree( lookupy[lookupinx] );
	  lookupy[lookupinx] = NULL;
	}
	lookupn[lookupinx] = 0;
      }
    }
    break;

#endif
#endif

  default:
    ERROR_MSG( "ioctl: ERROR - invalid IOCTL!\n" );
    rc = -ENOTTY;

  }

  mutex_unlock( &mutex );

  return rc;
}



///////////////////////////////////////////////////////////////////////////////
// *** DRIVER FUNCTIONS ***
///////////////////////////////////////////////////////////////////////////////

int dynclampmodule_open( struct inode *devFile, struct file *fModule )
{
  DEBUG_MSG( "================================================\n" );

#ifdef ENABLE_COMPUTATION
  memcpy( origParamOutput, paramOutput, sizeof(paramOutput) );
#endif
  return 0;
}


int dynclampmodule_close( struct inode *devFile, struct file *fModule )
{
  int iS;

  // no subdevice specified? => stop & close all subdevices & comedi-devices:
  if ( reqCloseSubdev < 0 ) {
    DEBUG_MSG( "dynclampmodule_close: no IOC_REQ_CLOSE request received - closing all subdevices...\n" );
    mutex_lock( &mutex );
    for ( iS = subdevN-1; iS>=0; iS-- )
      releaseSubdevice( subdevices[iS] );
    init_globals();
    mutex_unlock( &mutex );
    return 0;
  }

  // stop & close specified subdevice (and device):
  mutex_lock( &mutex );
  releaseSubdevice( reqCloseSubdev );
  DEBUG_MSG( "dynclampmodule_close: closed subdevice %d\n", reqCloseSubdev );
  if ( subdevN <= 0 )
    init_globals();
  reqCloseSubdev = -1;
  mutex_unlock( &mutex );
  return 0;
}


static int __init init_dynclampmodule( void )
{
  dev_t dev = 0;
  int retVal = 0;
#ifdef ENABLE_COMPUTATION
#ifdef ENABLE_LOOKUPTABLES
  int k;
#endif
#endif

  // register module device file:
  dev = MKDEV( RTMODULE_MAJOR, 0 );
  retVal = register_chrdev_region( dev, 1, "dynclamp" );
  if ( retVal < 0 ) {
    WARN_MSG( "init_dynclampmodule: can't get major %d\n", RTMODULE_MAJOR );
    return retVal;
  }
   
  rtcdev = cdev_alloc();
  rtcdev->ops = &fops;
  rtcdev->owner = THIS_MODULE;
  retVal = cdev_add( rtcdev, dev, 1 );
  if ( retVal )
    ERROR_MSG( "init_dynclampmodule: fail to register module with error %d\n", retVal );
  INFO_MSG( "init_dynclampmodule: dynamic clamp module loaded\n" );

  comedi_loglevel( 3 ); 

  mutex_init( &mutex );

#ifdef ENABLE_COMPUTATION
  memcpy( paramOutput, origParamOutput, sizeof(origParamOutput) );
#ifdef ENABLE_LOOKUPTABLES
  for ( k=0; k<MAXLOOKUPTABLES; k++ ) {
    lookupn[k] = 0;
    lookupx[lookupinx] = NULL;
    lookupy[lookupinx] = NULL;
  }
#endif
#endif

  // initialize global variables:
  init_globals();

  return retVal;
}


static void __exit cleanup_dynclampmodule( void )
{
  int iS;
  dev_t dev = MKDEV( RTMODULE_MAJOR, 0 );

  INFO_MSG( "cleanup_dynclampmodule: dynamic clamp module unloaded\n" );

  // stop and release all subdevices & comedi-devices:
  mutex_lock( &mutex );
  for ( iS = subdevN-1; iS>=0; iS-- )
    releaseSubdevice( subdevices[iS] );
  init_globals();
  mutex_unlock( &mutex );

  mutex_destroy( &mutex );

  // unregister module device file:
  cdev_del( rtcdev );
  unregister_chrdev_region( dev, 1 );
}

module_init( init_dynclampmodule );
module_exit( cleanup_dynclampmodule );


