#ifndef _REGISTER_H_
#define _REGISTER_H_

/* Addresses of the STC and board registers: */

#define Serial_Command				13
#define Misc_Command                            15
#define	Status                                  1
#define	Strobes_Register			1
#define	AI_AO_Select_Register			9
#define	Channel_A_Mode_Register			3
#define	ADC_FIFO_Data_Register                  28
#define	Configuration_Memory_Low                16
#define	Configuration_Memory_High               18
#define	AO_Configuration_Register               22
#define	AO_DAC_FIFO_Data                        30
#define	AO_DAC_0_Data_Register                  24
#define	AO_DAC_1_Data_Register                  26
#define	Strobes                                 1
#define	Channel_A_Mode                          3
#define	Channel_B_Mode                          5
#define	Channel_C_Mode                          7
#define	AI_AO_Select                            9
#define	G0_G1_Select                            11
#define	Configuration_Memory_Clear              130
#define	ADC_FIFO_Clear                          131
#define	DAC_FIFO_Clear	                        132
#define	AI_Command_1_Register			8
#define	AI_Command_2_Register			4
#define	AI_DIV_Load_A_Register			64
#define	AI_DIV_Save_Register			26
#define	AI_Mode_1_Register			12
#define	AI_Mode_2_Register			13
#define	AI_Mode_3_Register			87
#define	AI_Output_Control_Register		60
#define	AI_Personal_Register			77
#define	AI_SC_Load_B_Registers			20
#define	AI_SC_Load_A_Registers			18
#define	AI_SC_Save_Registers			66
#define	AI_SI_Load_B_Registers			16
#define	AI_SI_Load_A_Registers			14
#define	AI_SI_Save_Registers			64
#define	AI_SI2_Load_B_Register			25
#define	AI_SI2_Load_A_Register			23
#define	AI_SI2_Save_Register			25
#define	AI_START_STOP_Select_Register		62
#define	AI_Status_1_Register			2
#define	AI_Status_2_Register			5
#define	AI_Trigger_Select_Register		63
#define	Analog_Trigger_Etc_Register		61
#define	AO_BC_Load_B_Registers			46
#define	AO_BC_Load_A_Registers			44
#define	AO_BC_Save_Registers			18
#define	AO_Command_1_Register			9
#define	AO_Command_2_Register			5
#define	AO_Mode_1_Register			38
#define	AO_Mode_2_Register			39
#define	AO_Mode_3_Register			70
#define	AO_Output_Control_Register		86
#define	AO_Personal_Register			78
#define	AO_START_Select_Register		66
#define	AO_Status_1_Register			3
#define	AO_Status_2_Register			6
#define	AO_Trigger_Select_Register		67
#define	AO_UC_Load_B_Registers			50
#define	AO_UC_Load_A_Registers			48
#define	AO_UC_Save_Registers			20
#define	AO_UI_Load_B_Registers			42
#define	AO_UI_Load_A_Registers			40
#define	AO_UI_Save_Registers			16
#define	AO_UI2_Load_B_Register			55
#define	AO_UI2_Load_A_Register			53
#define	AO_UI2_Save_Register			23
#define	Clock_and_FOUT_Register			56
#define	DIO_Control_Register			11
#define	DIO_Output_Register			10
#define	DIO_Parallel_Input_Register		7
#define	DIO_Serial_Input_Register		28
#define	G_Status_Register			4
#define	G0_Autoincrement_Register		68
#define	G0_Command_Register			6
#define	G0_HW_Save_Registers			8
#define	G0_Input_Select_Register		36
#define	G0_Load_B_Registers			30
#define	G0_Load_A_Registers			28
#define	G0_Mode_Register			26
#define	G0_Save_Registers			12
#define	G1_Autoincrement_Register		69
#define	G1_Command_Register			7
#define	G1_HW_Save_Registers			10
#define	G1_Input_Select_Register		37
#define	G1_Load_B_Registers			34
#define	G1_Load_A_Registers			32
#define	G1_Mode_Register			27
#define	G1_Save_Registers			14
#define	Generic_Control_Register		71
#define	Interrupt_A_Ack_Register		2
#define	Interrupt_B_Ack_Register		3
#define	Interrupt_B_Enable_Register		75
#define	Interrupt_Control_Register		59
#define	Interrupt_A_Enable_Register		73
#define	IO_Bidirection_Pin_Register		57
#define	Joint_Reset_Register			72
#define	Joint_Status_1_Register			27
#define	Joint_Status_2_Register			29
#define	RTSI_Board_Register			81
#define	RTSI_Trig_B_Output_Register		80
#define	RTSI_Trig_Direction_Register	        58
#define	RTSI_Trig_A_Output_Register		79
#define	Second_Irq_A_Enable_Register	        74
#define	Second_Irq_B_Enable_Register	        76
#define	Window_Address_Register			0
#define	Window_Data_Read_Register		1
#define	Window_Data_Write_Register		1
#define	Write_Strobe_0_Register			82
#define	Write_Strobe_1_Register			83
#define	Write_Strobe_2_Register			84
#define	Write_Strobe_3_Register			85

#endif
