#!/bin/bash

# Obsolete! Is included in relacsscript!

###############################################################################
#
# autoemailbugs
# 
#
# RELACS - RealTime ELectrophysiological data Acquisition, Control, and Stimulation
# Copyright (C) 2002-2008 Jan Benda <j.benda@biologie.hu-berlin.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# RELACS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

LOGFILE=relacs.log
MAILCMD="mail -s RELACS_bugs j.benda@biologie.hu-berlin.de"

egrep 'error|warning|panic' $LOGFILE > tmp.txt
if [ "$(wc -l tmp.txt | awk '{print $1}' )" -gt 0 ]; then
  { sed -n '4,4p' $LOGFILE
    echo
    cat tmp.txt
  } | $MAILCMD
  rm tmp.txt
fi
