#!/bin/bash

###############################################################################
#
# createhelp
# 
#
# RELACS - RealTime ELectrophysiological data Acquisition, Control, and Stimulation
# Copyright (C) 2002-2007 Jan Benda <j.benda@biologie.hu-berlin.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# RELACS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

HELPDIR=$1

echo

LASTFILE=""
for DOXYFILES in doc/html/class*.html; do
  FILENAME=${DOXYFILES%.html}
  CLASSNAME=${FILENAME#doc/html/class}
  CLASSNAME=${CLASSNAME%-*}
  if [ "$CLASSNAME" != "es" ] && [ "$CLASSNAME" != "$LASTFILE" ]; then
    echo "create help file for $CLASSNAME..."
    { echo "<html><body>"
	echo "<h2>$CLASSNAME</h2>"
	sed -n -e '/<hr><a name="_details"/,/<hr>/p' $DOXYFILES | sed '1d; $d'
	echo "</body></html>"; 
    } > $HELPDIR/$CLASSNAME.html
    LASTFILE=$CLASSNAME
  fi
done
cp doc/html/*.jpg doc/html/*.png doc/html/*.gif $HELPDIR
exit 0

