#! /bin/sh
if [ $# -ne 3 ]; then
    echo "USAGE: $0 <property> <value to append> <directory>"
    exit 1
fi

PROP=$1
VALUE=$2
DIR=$3

TMP=`mktemp /tmp/tfile.XXXXXXXXXX`
if [ "x${TMP}" = x ]; then
    exit 1
fi
 
(svn propget "${PROP}" "${DIR}" && echo "${VALUE}") | sed '/^$/d' | sort -u > "${TMP}"
cat "${TMP}" | sed 's/^/  /'
svn propset --file "${TMP}" "${PROP}" "${DIR}"
rm "${TMP}"

exit 0

