#!/bin/bash

###############################################################################
#
# updategpl
# 
#
# RELACS - Relaxed ELectrophysiological data Acquisition, Control, and Stimulation
# Copyright (C) 2002-2009 Jan Benda <j.benda@biologie.hu-berlin.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# RELACS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################


function rewritegpl
{
    FILE="$1"
    if test -f "$FILE" && fgrep -q 'Copyright (C) 2002' "$FILE"; then
	sed -e 's/2002-20[0-9][0-9] Jan Benda/2002-2010 Jan Benda/' "$FILE" > tmp.txt
	mv tmp.txt "$FILE"
    fi
}

# help:
if test "$1" = "--help"; then
  echo "updategpl"
  echo
  echo "Run this script from the relacs base directory!"
  echo "Note: enable the examples beforehand:"
  echo "./configure --enable-examples"
  echo "and adapt the sed line to the right year."
  exit 0
fi

# .h
for i in $(find -name '*.h'); do
  rewritegpl $i
done

# .cc
for i in $(find -name '*.cc'); do
  rewritegpl $i
done

make distclean

# scripts:
# XXX need o keep permissions!!!
for i in $(find -name '*' -type f | grep -v '^\..*\.' | egrep -v 'Makefile|Doxyfile|configure|compile|missing|depcomp|updategpl'); do
  rewritegpl $i
done

# restoresome of the permissions:
./config.status
