#!/bin/bash

###############################################################################
#
# updategpl
# 
#
# RELACS - Relaxed ELectrophysiological data Acquisition, Control, and Stimulation
# Copyright (C) 2002-2012 Jan Benda <benda@bio.lmu.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# RELACS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################


function rewritegpl
{
    VERBOSE="no";
    if test "x$1" = "x-v"; then
	VERBOSE="yes"
	shift;
    fi
    FILE="$1"
    if test -f "$FILE" && fgrep -q 'Copyright (C) 200' "$FILE"; then
	test $VERBOSE = yes && ls -l "$FILE"
	sed -i -e 's/2002-20[0-9][0-9] Jan Benda/2002-2012 Jan Benda/' "$FILE"
    fi
}

# help:
if test "$1" = "--help"; then
  echo "updategpl"
  echo
  echo "Run this script from the relacs base directory!"
  echo "Note: enable the examples beforehand:"
  echo "./configure --enable-examples"
  echo "and adapt the sed line to the right year."
  exit 0
fi

# .h
for i in $(find -name '*.h'); do
  rewritegpl "$i"
done

# .cc
for i in $(find -name '*.cc'); do
  rewritegpl "$i"
done

# .c
for i in $(find -name '*.c'); do
  rewritegpl "$i"
done

# scripts:
# XXX need to keep permissions!!! Should work now, with the -i option for sed
echo "check permissions for the following updated files:"
for i in $(find -name '*' -type f | grep -v '^\..*\.' | egrep -v 'Makefile|Doxyfile|configure|compile|missing|depcomp|libtool|updategpl'); do
  rewritegpl -v "$i"
done

echo "check content of the following files for additional copyright statements:"
echo "src/relacs_head"
echo "src/relacslocal_head"
echo "doc/relacs.1"
echo "utils/updategpl"

# restore some of the permissions:
./config.status > /dev/null

make distclean > /dev/null
